version: "3.9"

services:
  db:
    image: postgres:14
    container_name: n8n-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/10-init-data.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  n8n:
    image: n8nio/n8n:1.48.1
    container_name: n8n
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    user: "1000:1000"                       # ← fix permission
    env_file:
      - .env
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_HOST: ${N8N_HOST}
      WEBHOOK_URL: ${WEBHOOK_URL}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}
      N8N_USER_FOLDER: /home/node/.n8n       # ← pastikan path user n8n
      GENERIC_TIMEZONE: ${TZ}
      TZ: ${TZ}
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    volumes:
      - ./data/n8n:/home/node/.n8n
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:${N8N_PORT}/healthz',res=>{process.exit(res.statusCode===200?0:1)})"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: n8n-net
